- hosts: sensor
  remote_user: root
  roles:
    - role: k3s
    - role: ca
    - role: nginx
    - role: sensorstack
    - role: kali
    - role: wireguard
    - role: fw
  vars:
    uri: sensor.local
    ldap:
      activate: true
      base_dn: dn=sensor,dc=local
    wireguard_port: 8128
